import "./globals.css";

export const metadata = {
  title: "Pumpions",
  description: "Generated by create next app",
  OpenGraph: {
    title: "Pumpions",
    description: "Generated by create next app",
    images: [
      {
        url: "/meta-image.webp",
        width: 800,
        height: 600,
      },
    ],
   
  }
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-grey" data-new-gr-c-s-check-loaded="14.1229.0" data-gr-ext-installed="">
        {children}
      </body>
    </html>
  );
}
